services:
  postgres:
    image: postgres:17.2
    container_name: postgres
    environment:
      POSTGRES_USER: menaget
      POSTGRES_PASSWORD: menaget
      POSTGRES_DB: menaget
    ports:
      - '6432:5432'
    networks:
      - menaget-net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U menaget -d menaget']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
    - postgres-data:/data

volumes:
  postgres-data: